name: Automation

on: [push, pull_request, workflow_dispatch]

jobs:
  fab:
    name: Fab Outputs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: INTI-CMNB/KiBot@v2_k9
      with:
        dir: output
        config: .github/kibot-fab.yaml
        verbose: 1
    - name: Full output
      id: everything
      uses: actions/upload-artifact@v4
      if: ${{ always() }}
      with:
        name: Everything
        path: output
    - name: Fab output
      id: fab
      uses: actions/upload-artifact@v4
      with:
        name: Fab
        compression-level: 9
        if-no-files-found: 'error'
        path: |
          output/*report.txt
          output/*.csv
          output/gerber/*

  diff:
    name: Difference
    runs-on: ubuntu-latest
    if: ${{ github.base_ref }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Tag PR base
      run: |
        git tag xxBASE ${{ github.event.pull_request.base.sha }}
        git log -n1 xxBASE
    - uses: INTI-CMNB/KiBot@v2_k9
      with:
        dir: diff
        config: .github/kibot-diff.yaml
        verbose: 3
    - name: Upload Diff
      id: diff
      uses: actions/upload-artifact@v4
      with:
        name: diff
        compression-level: 9
        if-no-files-found: 'error'
        path: diff

  publish:
    runs-on: ubuntu-latest

    if: github.ref=='refs/heads/main'
    needs: fab

    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.everything.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
